services:
  app:
    build: .
    image: riskintel:latest
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
    volumes:
      - ./data:/app/data
      - ./reports:/app/reports
      - ./logs:/app/logs
